WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

identifier = { (LETTER|"_")+ }
number = @{ "-"? ~ NUMBER+ }
string = @{ ("\"" ~ (!"\"" ~ ANY)* ~ "\"") | ("'" ~ (!"'" ~ ANY)* ~ "'") }
symbol = @{ ":" ~ LETTER+ }

program = { SOI ~ block ~ EOI }
block = { statement* }

statement = { (definition|binding|import|expression) }

binding = { "let" ~ identifier ~ "=" ~ expression }
definition = { "def" ~ identifier ~ "(" ~ (identifier ~ ("," ~ identifier)*)? ~ ")" ~ "{" ~ block ~ "}" }

import = { "import" ~ "{" ~ imported_symbol ~ ("," ~ imported_symbol)* ~ "}" ~ "from" ~ string }
imported_symbol = { identifier ~ ("as" ~ identifier)? }

expression = { expression_term ~ (operator ~ expression_term)* }
expression_term = { (array_index | object_index | function_call | value | "("~expression~")") }

value = _{ identifier | array | object | literal }

function_call = { identifier ~ "(" ~ argument_list? ~ ")" }
argument_list = _{ argument ~ ("," ~ argument)* }
argument = { identifier ~ ":" ~ expression }

literal = { number | string | symbol }

array = { "[" ~ array_members? ~ "]" }
array_members = _{ expression ~ ("," ~ expression)* }
array_index = { (function_call | identifier | array) ~ "[" ~ expression ~ "]" }

object = { "{" ~ object_members? ~ "}" }
object_members = _{ object_member ~ ("," ~ object_member)* }
object_member = { identifier ~ ":" ~ expression }
object_index = { (function_call | identifier | object) ~ "." ~ identifier }

operator = _{ multiply | concatenate | add }
concatenate = { "++" }
add = { "+" }
multiply = { "*" }
