WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

program = { SOI ~ block ~ EOI }
block = { statement* }

statement = { (definition_statement|binding_statement|expression_statement) }

binding_statement = { "let" ~ identifier ~ "=" ~ expression }
expression_statement = { expression }

definition_statement = { "def" ~ identifier ~ "(" ~ parameter_list? ~ ")" ~ "{" ~ block ~ "}" }
parameter_list = _{ parameter ~ ("," ~ parameter)* }
parameter = { identifier }

expression = { expression_term ~ (operator ~ expression_term)? }
expression_term = { (function_call | identifier | literal | "("~expression~")") }

function_call = { identifier ~ "(" ~ argument_list? ~ ")" }
argument_list = _{ argument ~ ("," ~ argument)* }
argument = { identifier ~ ":" ~ expression }

identifier = { (LETTER|"_")+ }
literal = { number | string | symbol }
number = @{ "-"? ~ NUMBER+ }
string = @{ ("\"" ~ (!"\"" ~ ANY)* ~ "\"") | ("'" ~ (!"'" ~ ANY)* ~ "'") }
symbol = @{ ":" ~ LETTER+ }

operator = { concatenation_operator | addition_operator | multiplication_operator }
concatenation_operator = { "++" }
addition_operator = { "+" }
multiplication_operator = { "*" }
